/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Capa_Presentación;

import Capa_Juzgado.DataApoderadoDemdd;
import Capa_Juzgado.DataApoderadoDemdt;
import Capa_Juzgado.DataDemandado;
import Capa_Juzgado.DataDemandante;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dcubi
 */
public class Apoderados extends javax.swing.JPanel {

    /**
     * Creates new form Detalle
     */
    public Apoderados() {
        initComponents();
        ListarApoderadoDemdd();
        ListarApoderadoDemdt();
        LimpiarCajasTexto();
    }
    
    public void LimpiarCajasTexto()
    {
        this.ID_apo.setText("");
        this.NomApo.setText("");
        this.Apeapon.setText("");
        this.TipIDapo.setText("");
        this.CorreoApo.setText("");
        this.DirecApo.setText("");
        this.Telapo.setText("");
        
        
        this.ID_apodeman.setText("");
        this.NomApodeman.setText("");
        this.Apeapondeman.setText("");
        this.TipIDapodeman.setText("");
        this.CorreoApodeman.setText("");
        this.DirecApodeman.setText("");
        this.Telapondeman.setText("");
    }
public void ListarApoderadoDemdd()
    {
        DefaultTableModel tabla1=new DefaultTableModel();
        DataApoderadoDemdd objAdem=new DataApoderadoDemdd();
        ArrayList<DataApoderadoDemdd> lista3=new ArrayList();
        lista3=objAdem.ListaApodeDemdd();
        tabla1.addColumn("ID");
        tabla1.addColumn("Nombre");
        tabla1.addColumn("Apellido");
        tabla1.addColumn("Tipo ID");
        tabla1.addColumn("Correo");
        tabla1.addColumn("Direccion");
        tabla1.addColumn("Telefono");
        tabla1.setRowCount(lista3.size());
        int i=0;
        for (DataApoderadoDemdd x: lista3) 
        {
            tabla1.setValueAt(x.getApoDemdd_ID(), i, 0);
            tabla1.setValueAt(x.getApoDemdd_Nom(), i, 1);
            tabla1.setValueAt(x.getApoDemdd_Apel(), i, 2);
            tabla1.setValueAt(x.getApoDemdd_TipoID(), i, 3);
            tabla1.setValueAt(x.getApoDemdd_Correo(), i, 4);
            tabla1.setValueAt(x.getApoDemdd_Direc(), i, 5);
            tabla1.setValueAt(x.getApoDemdd_Telef(), i, 6);
            i++;
        }
        
    }

public void ListarApoderadoDemdt()
    {
        DefaultTableModel tabla1=new DefaultTableModel();
        DataApoderadoDemdt objAdem=new DataApoderadoDemdt();
        ArrayList<DataApoderadoDemdt> lista3=new ArrayList();
        lista3=objAdem.ListaApoDemdt();
        tabla1.addColumn("ID");
        tabla1.addColumn("Nombre");
        tabla1.addColumn("Apellido");
        tabla1.addColumn("Tipo ID");
        tabla1.addColumn("Correo");
        tabla1.addColumn("Direccion");
        tabla1.addColumn("Telefono");
        tabla1.setRowCount(lista3.size());
        int i=0;
        for (DataApoderadoDemdt x: lista3) 
        {
            tabla1.setValueAt(x.getApoDemdt_ID(), i, 0);
            tabla1.setValueAt(x.getApoDemdt_Nom(), i, 1);
            tabla1.setValueAt(x.getApoDemdt_Apel(), i, 2);
            tabla1.setValueAt(x.getApoDemdt_TipoID(), i, 3);
            tabla1.setValueAt(x.getApoDemdt_Correo(), i, 4);
            tabla1.setValueAt(x.getApoDemdt_Direc(), i, 5);
            tabla1.setValueAt(x.getApoDemdt_Telef(), i, 6);
            i++;
        }
        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        NomApotex = new javax.swing.JLabel();
        NomApo = new javax.swing.JTextField();
        DNIapotex = new javax.swing.JLabel();
        TipIDapo = new javax.swing.JTextField();
        DirecApotex = new javax.swing.JLabel();
        DirecApo = new javax.swing.JTextField();
        Telapotex = new javax.swing.JLabel();
        Telapo = new javax.swing.JTextField();
        CorreoApotex = new javax.swing.JLabel();
        CorreoApo = new javax.swing.JTextField();
        ID_apotex = new javax.swing.JLabel();
        ID_apo = new javax.swing.JTextField();
        ID_apodemantex = new javax.swing.JLabel();
        ID_apodeman = new javax.swing.JTextField();
        NomApodeman = new javax.swing.JTextField();
        NomApodemantex = new javax.swing.JLabel();
        TipIDapodeman = new javax.swing.JTextField();
        DNIapodemantex = new javax.swing.JLabel();
        DirecApodeman = new javax.swing.JTextField();
        DirecApodemantex = new javax.swing.JLabel();
        Telapondeman = new javax.swing.JTextField();
        Telapondemantex = new javax.swing.JLabel();
        CorreoApodeman = new javax.swing.JTextField();
        CorreoApodemantex = new javax.swing.JLabel();
        Titulo1 = new javax.swing.JLabel();
        Titulo2 = new javax.swing.JLabel();
        confirmarbutton = new javax.swing.JButton();
        Apeapon = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Apeapondeman = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        bg.setBackground(new java.awt.Color(255, 255, 255));

        NomApotex.setText("Nombre");

        DNIapotex.setText("Tipo id");

        DirecApotex.setText("Direccion");

        Telapotex.setText("Telefono");

        CorreoApotex.setText("Correo electronico");

        ID_apotex.setText("ID_Apoderado");

        ID_apodemantex.setText("ID_Apoderado");

        NomApodemantex.setText("Nombre");

        DNIapodemantex.setText("Tipo id");

        DirecApodemantex.setText("Direccion");

        Telapondemantex.setText("Telefono");

        CorreoApodemantex.setText("Correo electronico");

        Titulo1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Titulo1.setText("Demandante");

        Titulo2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Titulo2.setText("Demandado");

        confirmarbutton.setBackground(new java.awt.Color(0, 102, 204));
        confirmarbutton.setForeground(new java.awt.Color(255, 255, 255));
        confirmarbutton.setText("Confirmar");
        confirmarbutton.setBorder(null);
        confirmarbutton.setBorderPainted(false);
        confirmarbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirmarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarbuttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Apellido");

        jLabel2.setText("Apellido");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                                .addComponent(ID_apotex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(154, 154, 154))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                                .addComponent(CorreoApotex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(138, 138, 138))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                                .addComponent(Telapotex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(190, 190, 190))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                                .addComponent(DirecApotex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(186, 186, 186))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                                .addComponent(DNIapotex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(216, 216, 216))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                                .addComponent(NomApotex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(192, 192, 192))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                                .addComponent(Titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(98, 98, 98))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TipIDapo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ID_apo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                                        .addComponent(NomApo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(bgLayout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(Apeapon)))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(Telapo))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(DirecApo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(CorreoApo)))
                .addGap(56, 56, 56)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(ID_apodemantex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(49, 49, 49))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(CorreoApodemantex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(33, 33, 33))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(Telapondemantex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(85, 85, 85))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(DirecApodemantex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(81, 81, 81))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(DNIapodemantex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(111, 111, 111))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(NomApodemantex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(87, 87, 87))
                            .addComponent(Titulo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(200, 200, 200))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ID_apodeman)
                            .addComponent(TipIDapodeman)
                            .addComponent(DirecApodeman)
                            .addComponent(Telapondeman)
                            .addComponent(CorreoApodeman)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                                .addComponent(NomApodeman, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(Apeapondeman))))
                        .addGap(95, 95, 95))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirmarbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Titulo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(ID_apodemantex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ID_apodeman)
                        .addGap(3, 3, 3)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomApodemantex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomApodeman)
                            .addComponent(Apeapondeman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DNIapodemantex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TipIDapodeman)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DirecApodemantex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DirecApodeman)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Telapondemantex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Telapondeman)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CorreoApodemantex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CorreoApodeman))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(ID_apotex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ID_apo)
                        .addGap(3, 3, 3)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomApotex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomApo)
                            .addComponent(Apeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DNIapotex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TipIDapo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DirecApotex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DirecApo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Telapotex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Telapo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CorreoApotex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CorreoApo)))
                .addGap(18, 18, 18)
                .addComponent(confirmarbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarbuttonActionPerformed
        DataApoderadoDemdt objart=new DataApoderadoDemdt();
        objart.setApoDemdt_ID(Integer.parseInt(this.ID_apo.getText()));
        objart.setApoDemdt_Nom(this.NomApo.getText());
        objart.setApoDemdt_Apel(this.Apeapon.getText());
        objart.setApoDemdt_TipoID(this.TipIDapo.getText());
        objart.setApoDemdt_Correo(this.CorreoApo.getText());
        objart.setApoDemdt_Direc(this.DirecApo.getText());
        objart.setApoDemdt_Telef(Integer.parseInt(this.Telapo.getText()));
        JOptionPane.showMessageDialog(null, objart.GuardarApoDemandante());
        ListarApoderadoDemdt();
        
        
       DataApoderadoDemdd objmed=new DataApoderadoDemdd();
        objmed.setApoDemdd_ID(Integer.parseInt(this.ID_apodeman.getText()));
        objmed.setApoDemdd_Nom(this.NomApodeman.getText());
        objmed.setApoDemdd_Apel(this.Apeapondeman.getText());
        objmed.setApoDemdd_TipoID(this.TipIDapodeman.getText());
        objmed.setApoDemdd_Correo(this.CorreoApodeman.getText());
        objmed.setApoDemdd_Direc(this.DirecApodeman.getText());
        objmed.setApoDemdd_Telef(Integer.parseInt(this.Telapondeman.getText()));
        JOptionPane.showMessageDialog(null, objmed.GuardarApoDemandado());
        ListarApoderadoDemdd();
    }//GEN-LAST:event_confirmarbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apeapon;
    private javax.swing.JTextField Apeapondeman;
    private javax.swing.JTextField CorreoApo;
    private javax.swing.JTextField CorreoApodeman;
    private javax.swing.JLabel CorreoApodemantex;
    private javax.swing.JLabel CorreoApotex;
    private javax.swing.JLabel DNIapodemantex;
    private javax.swing.JLabel DNIapotex;
    private javax.swing.JTextField DirecApo;
    private javax.swing.JTextField DirecApodeman;
    private javax.swing.JLabel DirecApodemantex;
    private javax.swing.JLabel DirecApotex;
    private javax.swing.JTextField ID_apo;
    private javax.swing.JTextField ID_apodeman;
    private javax.swing.JLabel ID_apodemantex;
    private javax.swing.JLabel ID_apotex;
    private javax.swing.JTextField NomApo;
    private javax.swing.JTextField NomApodeman;
    private javax.swing.JLabel NomApodemantex;
    private javax.swing.JLabel NomApotex;
    private javax.swing.JTextField Telapo;
    private javax.swing.JTextField Telapondeman;
    private javax.swing.JLabel Telapondemantex;
    private javax.swing.JLabel Telapotex;
    private javax.swing.JTextField TipIDapo;
    private javax.swing.JTextField TipIDapodeman;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JPanel bg;
    private javax.swing.JButton confirmarbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
