
import java.awt.BorderLayout;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JPanel;
import Capa_Presentación.Apoderados;
import Capa_Presentación.Detalles_Deman;
import Capa_Presentación.Detalles_Pesona_Demanda;
import Capa_Presentación.Modificar_Demandado;
import Capa_Presentación.Modificar_Demandante;
import Capa_Presentación.Principal;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dcubi
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        SetDate();
        InitContent();
    }
    
    private void SetDate(){
        LocalDate now = LocalDate.now();
        Locale spanishlocale = new Locale("es","ES"); 
        FechaLabel.setText(now.format(DateTimeFormatter.ofPattern("EEEE','dd 'de' MMMM 'de' YYYY",spanishlocale)));
    }

    private void InitContent(){
        
        showJPanel(new Principal());
        
    }

    
    private void showJPanel(JPanel p){
        p.setSize(1400, 525);
        p.setLocation(0, 0);
        
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroud = new javax.swing.JPanel();
        Login = new javax.swing.JPanel();
        FechaLabel = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        AgregApon = new javax.swing.JButton();
        Detallesdeman = new javax.swing.JButton();
        DatalleProc = new javax.swing.JButton();
        Principalbutton1 = new javax.swing.JButton();
        Modifpanelbutton2 = new javax.swing.JButton();
        Modifpanelbutton1 = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1030, 650));

        backgroud.setBackground(new java.awt.Color(255, 255, 255));

        Login.setBackground(new java.awt.Color(29, 82, 176));

        FechaLabel.setForeground(new java.awt.Color(255, 255, 255));
        FechaLabel.setText("{dayname}, {day} de {month} de {year}");

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(FechaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FechaLabel)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        header.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );

        menu.setBackground(new java.awt.Color(29, 82, 176));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AgregApon.setBackground(new java.awt.Color(29, 82, 176));
        AgregApon.setForeground(new java.awt.Color(255, 255, 255));
        AgregApon.setText("Agregar Apoderados");
        AgregApon.setBorder(null);
        AgregApon.setBorderPainted(false);
        AgregApon.setContentAreaFilled(false);
        AgregApon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AgregApon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregAponActionPerformed(evt);
            }
        });
        menu.add(AgregApon, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 160, 50));

        Detallesdeman.setBackground(new java.awt.Color(29, 82, 176));
        Detallesdeman.setForeground(new java.awt.Color(255, 255, 255));
        Detallesdeman.setText("Detalles de la demanda");
        Detallesdeman.setBorder(null);
        Detallesdeman.setContentAreaFilled(false);
        Detallesdeman.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Detallesdeman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetallesdemanActionPerformed(evt);
            }
        });
        menu.add(Detallesdeman, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 160, 50));

        DatalleProc.setBackground(new java.awt.Color(29, 82, 176));
        DatalleProc.setForeground(new java.awt.Color(255, 255, 255));
        DatalleProc.setText("Detalles Proceso");
        DatalleProc.setBorder(null);
        DatalleProc.setBorderPainted(false);
        DatalleProc.setContentAreaFilled(false);
        DatalleProc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DatalleProc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatalleProcActionPerformed(evt);
            }
        });
        menu.add(DatalleProc, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 160, 50));

        Principalbutton1.setBackground(new java.awt.Color(29, 82, 176));
        Principalbutton1.setForeground(new java.awt.Color(255, 255, 255));
        Principalbutton1.setText("Principal");
        Principalbutton1.setBorder(null);
        Principalbutton1.setBorderPainted(false);
        Principalbutton1.setContentAreaFilled(false);
        Principalbutton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Principalbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Principalbutton1ActionPerformed(evt);
            }
        });
        menu.add(Principalbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 50));

        Modifpanelbutton2.setBackground(new java.awt.Color(29, 82, 176));
        Modifpanelbutton2.setForeground(new java.awt.Color(255, 255, 255));
        Modifpanelbutton2.setText("Modificar Dmdt");
        Modifpanelbutton2.setBorder(null);
        Modifpanelbutton2.setBorderPainted(false);
        Modifpanelbutton2.setContentAreaFilled(false);
        Modifpanelbutton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Modifpanelbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modifpanelbutton2ActionPerformed(evt);
            }
        });
        menu.add(Modifpanelbutton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 160, 50));

        Modifpanelbutton1.setBackground(new java.awt.Color(29, 82, 176));
        Modifpanelbutton1.setForeground(new java.awt.Color(255, 255, 255));
        Modifpanelbutton1.setText("Modificar Dmdd");
        Modifpanelbutton1.setBorder(null);
        Modifpanelbutton1.setBorderPainted(false);
        Modifpanelbutton1.setContentAreaFilled(false);
        Modifpanelbutton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Modifpanelbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modifpanelbutton1ActionPerformed(evt);
            }
        });
        menu.add(Modifpanelbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 160, 50));

        content.setMinimumSize(new java.awt.Dimension(0, 454));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroudLayout = new javax.swing.GroupLayout(backgroud);
        backgroud.setLayout(backgroudLayout);
        backgroudLayout.setHorizontalGroup(
            backgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        backgroudLayout.setVerticalGroup(
            backgroudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroudLayout.createSequentialGroup()
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Modifpanelbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modifpanelbutton2ActionPerformed
        showJPanel(new Modificar_Demandante());
    }//GEN-LAST:event_Modifpanelbutton2ActionPerformed

    private void AgregAponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregAponActionPerformed
        showJPanel(new Apoderados());
    }//GEN-LAST:event_AgregAponActionPerformed

    private void DetallesdemanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetallesdemanActionPerformed
        showJPanel(new Detalles_Deman());
    }//GEN-LAST:event_DetallesdemanActionPerformed

    private void DatalleProcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatalleProcActionPerformed
        showJPanel(new Detalles_Pesona_Demanda());
    }//GEN-LAST:event_DatalleProcActionPerformed

    private void Principalbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Principalbutton1ActionPerformed
        showJPanel(new Principal());
    }//GEN-LAST:event_Principalbutton1ActionPerformed

    private void Modifpanelbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modifpanelbutton1ActionPerformed
        showJPanel(new Modificar_Demandado());
    }//GEN-LAST:event_Modifpanelbutton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregApon;
    private javax.swing.JButton DatalleProc;
    private javax.swing.JButton Detallesdeman;
    private javax.swing.JLabel FechaLabel;
    private javax.swing.JPanel Login;
    private javax.swing.JButton Modifpanelbutton1;
    private javax.swing.JButton Modifpanelbutton2;
    private javax.swing.JButton Principalbutton1;
    private javax.swing.JPanel backgroud;
    private javax.swing.JPanel content;
    private javax.swing.JPanel header;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
