/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Capa_Presentación;

import Capa_Juzgado.DataDetalleProceso;
import Capa_Juzgado.DataDemandado;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dcubi
 */
public class Detalles_Pesona_Demanda extends javax.swing.JPanel {

    /**
     * Creates new form Detalles_Deman
     */
    public Detalles_Pesona_Demanda() {
        initComponents();
        ListarDetalleProceso();
        
    }
    public void ListarDetalleProceso()
    {
        DefaultTableModel tabla1=new DefaultTableModel();
        DataDetalleProceso objdem=new DataDetalleProceso();
        ArrayList<DataDetalleProceso> lista6=new ArrayList();
        lista6=objdem.ListaDetalleproceso();
        tabla1.addColumn("Num_Detalle");
        tabla1.addColumn("Estado");
        tabla1.addColumn("Num_Radicado");
        tabla1.addColumn("ID_Demdt");
        tabla1.addColumn("ID_ApoDemdt");
        tabla1.addColumn("ID_Demdd");
        tabla1.addColumn("ID_ApoDemdd");
        tabla1.setRowCount(lista6.size());
        int i=0;
        for (DataDetalleProceso x: lista6) 
        {
            tabla1.setValueAt(x.getDetalle_numdetalle(), i, 0);
            tabla1.setValueAt(x.getDetalle_estado(), i, 1);
            tabla1.setValueAt(x.getDetalle_fknumradi(), i, 2);
            tabla1.setValueAt(x.getDetalle_fkiddemandante(), i, 3);
            tabla1.setValueAt(x.getDetalle_fkidapdemandante(), i, 4);
            tabla1.setValueAt(x.getDetalle_fkiddemandado(), i, 5);
            tabla1.setValueAt(x.getDetalle_fkidapdemandado(), i, 6);
            i++;
        }
        this.Tabla_Detalle.setModel(tabla1);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Detalle = new javax.swing.JTable();
        Titulo = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Tabla_Detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tabla_Detalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Tabla_DetalleMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_Detalle);

        Titulo.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        Titulo.setText("Detalle Proceso");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(362, 362, 362))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                        .addGap(462, 462, 462))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Tabla_DetalleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_DetalleMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tabla_DetalleMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_Detalle;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
