/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Capa_Presentación;

import Capa_Juzgado.DataDemandado;
import Capa_Juzgado.DataDemandante;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dcubi
 */
public class Modificar_Demandado extends javax.swing.JPanel {

    /**
     * Creates new form Modificar
     */
    public Modificar_Demandado() {
        initComponents();
        ListarDemandado();
        LimpiarCajasTexto();
    }
    public void LimpiarCajasTexto()
    {
        this.ID.setText("");
        this.Nom.setText("");
        this.ID.setText("");
        this.TipoID.setText("");
        this.Correo.setText("");
        this.Direc.setText("");
        this.Telef.setText("");
       
    }
    
    
            
    
    
    
    public void ListarDemandado()
    {
        DefaultTableModel tabla1=new DefaultTableModel();
        DataDemandado objdem=new DataDemandado();
        ArrayList<DataDemandado> lista3=new ArrayList();
        lista3=objdem.ListaDemandado();
        tabla1.addColumn("ID");
        tabla1.addColumn("Nombre");
        tabla1.addColumn("Apellido");
        tabla1.addColumn("Tipo ID");
        tabla1.addColumn("Correo");
        tabla1.addColumn("Direccion");
        tabla1.addColumn("Telefono");
        tabla1.setRowCount(lista3.size());
        int i=0;
        for (DataDemandado x: lista3) 
        {
            tabla1.setValueAt(x.getDemdd_ID(), i, 0);
            tabla1.setValueAt(x.getDemdd_Nom(), i, 1);
            tabla1.setValueAt(x.getDemdd_Apel(), i, 2);
            tabla1.setValueAt(x.getDemdd_TipoID(), i, 3);
            tabla1.setValueAt(x.getDemdd_Correo(), i, 4);
            tabla1.setValueAt(x.getDemdd_Direc(), i, 5);
            tabla1.setValueAt(x.getDemdd_Telef(), i, 6);
            i++;
        }
        this.jTable1.setModel(tabla1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Buscartex = new javax.swing.JTextField();
        Buscarbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Nom = new javax.swing.JTextField();
        Nomtex = new javax.swing.JLabel();
        DNItex = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        Directex = new javax.swing.JLabel();
        Direc = new javax.swing.JTextField();
        Teleftex = new javax.swing.JLabel();
        Telef = new javax.swing.JTextField();
        Correotex = new javax.swing.JLabel();
        Correo = new javax.swing.JTextField();
        Estadtex = new javax.swing.JLabel();
        Estad = new javax.swing.JTextField();
        Modificarbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TipoID = new javax.swing.JTextField();
        Apellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        Buscartex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscartexActionPerformed(evt);
            }
        });

        Buscarbutton.setBackground(new java.awt.Color(0, 102, 204));
        Buscarbutton.setForeground(new java.awt.Color(255, 255, 255));
        Buscarbutton.setText("Buscar");
        Buscarbutton.setBorder(null);
        Buscarbutton.setBorderPainted(false);
        Buscarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarbuttonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Nomtex.setText("Nombre");

        DNItex.setText("ID");

        Directex.setText("Direccion");

        Direc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirecActionPerformed(evt);
            }
        });

        Teleftex.setText("Telefono");

        Correotex.setText("Correo electronico");

        Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoActionPerformed(evt);
            }
        });

        Estadtex.setText("Estado");

        Estad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadActionPerformed(evt);
            }
        });

        Modificarbutton.setBackground(new java.awt.Color(0, 102, 204));
        Modificarbutton.setForeground(new java.awt.Color(255, 255, 255));
        Modificarbutton.setText("Modificar");
        Modificarbutton.setBorder(null);
        Modificarbutton.setBorderPainted(false);
        Modificarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarbuttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo ID");

        TipoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoIDActionPerformed(evt);
            }
        });

        jLabel2.setText("Apellido");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(DNItex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(563, 563, 563))
                            .addComponent(Buscartex, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(614, 614, 614)
                        .addComponent(Buscarbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(Nomtex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(162, 162, 162))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(ID)
                                        .addGap(58, 58, 58))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(Nom)
                                        .addGap(11, 11, 11)))
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(Directex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(173, 173, 173))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Apellido, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Direc))
                                        .addGap(41, 41, 41))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(Modificarbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(147, 147, 147)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(TipoID))
                                .addGap(67, 67, 67)))
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(Correo)
                                .addGap(13, 13, 13))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(Estadtex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(Teleftex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(131, 131, 131))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(Estad)
                                .addGap(50, 50, 50))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(Telef)
                                .addGap(52, 52, 52))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(Correotex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buscartex, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscarbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Teleftex, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Nomtex, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Estadtex, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DNItex, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Directex, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Estad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Direc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Modificarbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(Correotex, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TipoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BuscartexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscartexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscartexActionPerformed

    private void ModificarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarbuttonActionPerformed
        System.out.println("");
        DataDemandado objart=new DataDemandado();
        objart.setDemdd_ID(Long.parseLong(this.ID.getText()));
        objart.setDemdd_Nom(this.Nom.getText());
        objart.setDemdd_Apel(this.Apellido.getText());
        objart.setDemdd_TipoID(this.TipoID.getText());
        objart.setDemdd_Correo(this.Correo.getText());
        objart.setDemdd_Direc(this.Direc.getText());
        objart.setDemdd_Telef(Long.parseLong(this.Telef.getText()));
        JOptionPane.showMessageDialog(null, objart.ModificarDemandd());
        ListarDemandado();
    }//GEN-LAST:event_ModificarbuttonActionPerformed

    private void DirecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DirecActionPerformed

    private void EstadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadActionPerformed

    private void CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        int rec=this.jTable1.getSelectedRow();
        this.ID.setText(jTable1.getValueAt(rec, 0).toString());
        this.Nom.setText(jTable1.getValueAt(rec, 1).toString());
        this.Apellido.setText(jTable1.getValueAt(rec,2).toString());
        this.TipoID.setText(jTable1.getValueAt(rec, 3).toString());
        this.Correo.setText(jTable1.getValueAt(rec, 4).toString());
        this.Direc.setText(jTable1.getValueAt(rec, 5).toString());
        this.Telef.setText(jTable1.getValueAt(rec, 6).toString());
    }//GEN-LAST:event_jTable1MousePressed

    private void TipoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoIDActionPerformed

    private void BuscarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarbuttonActionPerformed

    }//GEN-LAST:event_BuscarbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido;
    private javax.swing.JButton Buscarbutton;
    private javax.swing.JTextField Buscartex;
    private javax.swing.JTextField Correo;
    private javax.swing.JLabel Correotex;
    private javax.swing.JLabel DNItex;
    private javax.swing.JTextField Direc;
    private javax.swing.JLabel Directex;
    private javax.swing.JTextField Estad;
    private javax.swing.JLabel Estadtex;
    private javax.swing.JTextField ID;
    private javax.swing.JButton Modificarbutton;
    private javax.swing.JTextField Nom;
    private javax.swing.JLabel Nomtex;
    private javax.swing.JTextField Telef;
    private javax.swing.JLabel Teleftex;
    private javax.swing.JTextField TipoID;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
