/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Capa_Presentación;

import Capa_Juzgado.DataDetalleProceso;
import Capa_Juzgado.DataDemandado;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dcubi
 */
public class Detalles_Pesona_Demanda extends javax.swing.JPanel {

    /**
     * Creates new form Detalles_Deman
     */
    public Detalles_Pesona_Demanda() {
        initComponents();
        ListarDetalleProceso();
        
    }
    public void ListarDetalleProceso()
    {
        DefaultTableModel tabla1=new DefaultTableModel();
        DataDetalleProceso objdem=new DataDetalleProceso();
        ArrayList<DataDetalleProceso> lista6=new ArrayList();
        lista6=objdem.ListaDetalleproceso();
        tabla1.addColumn("Estado");
        tabla1.addColumn("Num_Radicado");
        tabla1.addColumn("ID_Demdt");
        tabla1.addColumn("ID_ApoDemdt");
        tabla1.addColumn("ID_Demdd");
        tabla1.addColumn("ID_ApoDemdd");
        tabla1.setRowCount(lista6.size());
        int i=0;
        for (DataDetalleProceso x: lista6) 
        {
            tabla1.setValueAt(x.getDetalle_estado(), i, 0);
            tabla1.setValueAt(x.getDetalle_fknumradi(), i, 1);
            tabla1.setValueAt(x.getDetalle_fkiddemandante(), i, 2);
            tabla1.setValueAt(x.getDetalle_fkidapdemandante(), i, 3);
            tabla1.setValueAt(x.getDetalle_fkiddemandado(), i, 4);
            tabla1.setValueAt(x.getDetalle_fkidapdemandado(), i, 5);
            i++;
        }
        this.Tabla_Detalle.setModel(tabla1);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Detalle = new javax.swing.JTable();
        Titulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Estado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        IdDemandante = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        IdDemandado = new javax.swing.JTextField();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Tabla_Detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tabla_Detalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Tabla_DetalleMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_Detalle);

        Titulo.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        Titulo.setText("Detalle Proceso");

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoActionPerformed(evt);
            }
        });
        Estado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EstadoKeyTyped(evt);
            }
        });

        jLabel1.setText("Estado");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En proceso", "Primera instancia", "Segunda instancia", "Archivado" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Id Demandante");

        IdDemandante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdDemandanteActionPerformed(evt);
            }
        });
        IdDemandante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IdDemandanteKeyTyped(evt);
            }
        });

        jLabel3.setText("Id Demandado");

        IdDemandado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdDemandadoActionPerformed(evt);
            }
        });
        IdDemandado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IdDemandadoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(44, 44, 44)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(IdDemandante, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(IdDemandado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(85, 85, 85))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                        .addGap(462, 462, 462))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(IdDemandante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(IdDemandado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Tabla_DetalleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_DetalleMousePressed
        // TODO add your handling code here:
        int rec=this.Tabla_Detalle.getSelectedRow();
        this.Estado.setText(Tabla_Detalle.getValueAt(rec, 0).toString());
        this.IdDemandante.setText(Tabla_Detalle.getValueAt(rec, 2).toString());
        this.IdDemandado.setText(Tabla_Detalle.getValueAt(rec, 4).toString());
    }//GEN-LAST:event_Tabla_DetalleMousePressed

    private void EstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadoActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:;
        int i =0;
        while(Estado.getText()!= "Archivado"&&i==0){
        String mensaje;
        mensaje=jComboBox1.getSelectedItem().toString();
        Estado.setText(mensaje);
        i++;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DataDetalleProceso objart = new DataDetalleProceso();
        objart.setDetalle_fkidapdemandado(Long.parseLong(this.IdDemandado.getText()));
        objart.setDetalle_fkiddemandante(Long.parseLong(this.IdDemandante.getText()));
        objart.setDetalle_estado(this.Estado.getText());
        JOptionPane.showMessageDialog(null, objart.ModificarDetalle());
        ListarDetalleProceso();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void IdDemandanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdDemandanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdDemandanteActionPerformed

    private void IdDemandadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdDemandadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdDemandadoActionPerformed

    private void IdDemandanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdDemandanteKeyTyped
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_IdDemandanteKeyTyped

    private void IdDemandadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdDemandadoKeyTyped
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_IdDemandadoKeyTyped

    private void EstadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EstadoKeyTyped
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_EstadoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Estado;
    private javax.swing.JTextField IdDemandado;
    private javax.swing.JTextField IdDemandante;
    private javax.swing.JTable Tabla_Detalle;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
