/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Capa_Presentación;

import Capa_Datos.Conexion;
import Capa_Juzgado.DataDemandante;
import java.util.ArrayList;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dcubi
 */
public class Modificar_Demandante extends javax.swing.JPanel {

    /**
     * Creates new form Modificar
     */
    public Modificar_Demandante() {
        initComponents();
        ListarDemandante();
        LimpiarCajasTexto();
    }
    public void LimpiarCajasTexto()
    {
        this.ID.setText("");
        this.Nom.setText("");
        this.ID.setText("");
        this.TipoID.setText("");
        this.Correo.setText("");
        this.Direc.setText("");
        this.Telef.setText("");
       
    }
    public void ListarDemandante()
    {
        DefaultTableModel tabla=new DefaultTableModel();
        DataDemandante objart=new DataDemandante();
        ArrayList<DataDemandante> lista2=new ArrayList();
        lista2=objart.ListaDemandante();
        tabla.addColumn("ID");
        tabla.addColumn("Nombre");
        tabla.addColumn("Tipo ID");
        tabla.addColumn("Correo");
        tabla.addColumn("Direccion");
        tabla.addColumn("Telefono");
        tabla.setRowCount(lista2.size());
        int i=0;
        for (DataDemandante x: lista2) 
        {
            tabla.setValueAt(x.getDemt_ID(), i, 0);
            tabla.setValueAt(x.getDemdt_Nom(), i, 1);
            tabla.setValueAt(x.getDemdt_TipoID(), i,2);
            tabla.setValueAt(x.getDemdt_Correo(), i, 3);
            tabla.setValueAt(x.getDemdt_Direc(), i, 4);
            tabla.setValueAt(x.getDemdt_Telef(), i, 5);
            i++;
        }
        this.jTable1.setModel(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Buscartex = new javax.swing.JTextField();
        Buscarbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Nom = new javax.swing.JTextField();
        Nomtex = new javax.swing.JLabel();
        DNItex = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        Directex = new javax.swing.JLabel();
        Direc = new javax.swing.JTextField();
        Teleftex = new javax.swing.JLabel();
        Telef = new javax.swing.JTextField();
        Correotex = new javax.swing.JLabel();
        Correo = new javax.swing.JTextField();
        Modificarbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TipoID = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();

        Buscartex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscartexActionPerformed(evt);
            }
        });
        Buscartex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscartexKeyTyped(evt);
            }
        });

        Buscarbutton.setBackground(new java.awt.Color(0, 102, 204));
        Buscarbutton.setForeground(new java.awt.Color(255, 255, 255));
        Buscarbutton.setText("Buscar");
        Buscarbutton.setBorder(null);
        Buscarbutton.setBorderPainted(false);
        Buscarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarbuttonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NomKeyTyped(evt);
            }
        });

        Nomtex.setText("Nombre");

        DNItex.setText("ID");

        ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IDKeyTyped(evt);
            }
        });

        Directex.setText("Direccion");

        Direc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirecActionPerformed(evt);
            }
        });
        Direc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DirecKeyTyped(evt);
            }
        });

        Teleftex.setText("Telefono");

        Telef.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefKeyTyped(evt);
            }
        });

        Correotex.setText("Correo electronico");

        Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoActionPerformed(evt);
            }
        });
        Correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CorreoKeyTyped(evt);
            }
        });

        Modificarbutton.setBackground(new java.awt.Color(0, 102, 204));
        Modificarbutton.setForeground(new java.awt.Color(255, 255, 255));
        Modificarbutton.setText("Modificar");
        Modificarbutton.setBorder(null);
        Modificarbutton.setBorderPainted(false);
        Modificarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarbuttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo ID");

        TipoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoIDActionPerformed(evt);
            }
        });
        TipoID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TipoIDKeyTyped(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "NIT", "CE" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(DNItex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(563, 563, 563))
                            .addComponent(Buscartex, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Modificarbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ID, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                    .addComponent(Nom))
                                .addGap(31, 31, 31)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Teleftex, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Telef, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Directex, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Correotex, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Direc, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                                .addComponent(Correo)))
                                        .addGap(65, 65, 65)
                                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(bgLayout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(TipoID, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(614, 614, 614)
                                .addComponent(Buscarbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Nomtex, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buscartex, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscarbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nomtex, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Directex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Direc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DNItex, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Correotex, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID)
                    .addComponent(Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TipoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Modificarbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Teleftex, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Telef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BuscartexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscartexActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BuscartexActionPerformed

    private void ModificarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarbuttonActionPerformed
        System.out.println("");
        DataDemandante objart=new DataDemandante();
        objart.setDemt_ID(Long.parseLong(this.ID.getText()));
        objart.setDemdt_Nom(this.Nom.getText());
        objart.setDemdt_TipoID(this.TipoID.getText());
        objart.setDemdt_Correo(this.Correo.getText());
        objart.setDemdt_Direc(this.Direc.getText());
        objart.setDemdt_Telef(Long.parseLong(this.Telef.getText()));
        JOptionPane.showMessageDialog(null, objart.ModificarDemandt());
        ListarDemandante();
    }//GEN-LAST:event_ModificarbuttonActionPerformed

    private void DirecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DirecActionPerformed

    private void CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        int rec=this.jTable1.getSelectedRow();
        this.ID.setText(jTable1.getValueAt(rec, 0).toString());
        this.Nom.setText(jTable1.getValueAt(rec, 1).toString());
        this.TipoID.setText(jTable1.getValueAt(rec, 2).toString());
        this.Correo.setText(jTable1.getValueAt(rec, 3).toString());
        this.Direc.setText(jTable1.getValueAt(rec, 4).toString());
        this.Telef.setText(jTable1.getValueAt(rec, 5).toString());
    }//GEN-LAST:event_jTable1MousePressed

    private void TipoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoIDActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
        String mensaje;
        mensaje=jComboBox4.getSelectedItem().toString();
        TipoID.setText(mensaje);
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void TipoIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TipoIDKeyTyped
        // TODO add your handling code here:
        evt.consume();
    }//GEN-LAST:event_TipoIDKeyTyped

    private void CorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CorreoKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;
        boolean espacio = key ==32;
        boolean punto = key == 46;
        boolean arroba = key == 64;
        boolean borrar = key ==27;
                boolean numeros = key >= 48 && key <= 57;
        if (!(minusculas||mayusculas||espacio||borrar||punto||arroba||numeros)) {
            evt.consume();
        }
      
    }//GEN-LAST:event_CorreoKeyTyped

    private void BuscartexKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscartexKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!(numeros)) {
            evt.consume();       
        }
    }//GEN-LAST:event_BuscartexKeyTyped

    private void IDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!(numeros)) {
            evt.consume();       
        }
    }//GEN-LAST:event_IDKeyTyped

    private void TelefKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!(numeros)) {
            evt.consume();     
        }
    }//GEN-LAST:event_TelefKeyTyped

    private void DirecKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DirecKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;
        boolean espacio = key ==32;
        boolean borrar = key ==27;
                boolean numeros = key >= 48 && key <= 57;
        if (!(minusculas||mayusculas||espacio||borrar||numeros)) {
            evt.consume();
        }
    }//GEN-LAST:event_DirecKeyTyped

    private void NomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;
        boolean espacio = key ==32;
        boolean borrar = key ==27;
        if (!(minusculas||mayusculas||espacio||borrar)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Debe digitar solo caracteres alfabeticos");
        }
    }//GEN-LAST:event_NomKeyTyped

    private void BuscarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarbuttonActionPerformed
        // TODO add your handling code here:
        Conexion con = new Conexion();
        DataDemandante objdem = new DataDemandante();
        long i = objdem.getDemt_ID();
        try {
            ResultSet cad = con.listar("Select * from Demandante where id_demandante = " + this.Buscartex.getText());

                while (cad.next()) {

                    ID.setText(cad.getString("id_demandante"));
                    Nom.setText(cad.getString("nombre"));
                    TipoID.setText(cad.getString("tipo_id"));
                    Correo.setText(cad.getString("correo_electronico"));
                    Direc.setText(cad.getString("direccion"));
                    Telef.setText(cad.getString("telefono"));
                }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_BuscarbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscarbutton;
    private javax.swing.JTextField Buscartex;
    private javax.swing.JTextField Correo;
    private javax.swing.JLabel Correotex;
    private javax.swing.JLabel DNItex;
    private javax.swing.JTextField Direc;
    private javax.swing.JLabel Directex;
    private javax.swing.JTextField ID;
    private javax.swing.JButton Modificarbutton;
    private javax.swing.JTextField Nom;
    private javax.swing.JLabel Nomtex;
    private javax.swing.JTextField Telef;
    private javax.swing.JLabel Teleftex;
    private javax.swing.JTextField TipoID;
    private javax.swing.JPanel bg;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
