/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Capa_Presentación;

import Capa_Datos.Conexion;
import Capa_Juzgado.DataDemandado;
import Capa_Juzgado.DataEmpleado;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dcubi
 */
public class Usuario extends javax.swing.JPanel {

    /**
     * Creates new form Usuario
     */
    public Usuario() {
        initComponents();
        llenado();
    }
    
    public void ListarDemandado()
    {
        DefaultTableModel tabla1=new DefaultTableModel();
        DataEmpleado objdem=new DataEmpleado();
        ArrayList<DataEmpleado> lista3=new ArrayList();
        lista3=objdem.ListaEmpl();
        tabla1.addColumn("ID");
        tabla1.addColumn("Nombre");
        tabla1.addColumn("Apellido");
        tabla1.addColumn("Tipo ID");
        tabla1.addColumn("Correo");
        tabla1.addColumn("Direccion");
        tabla1.addColumn("Telefono");
        tabla1.setRowCount(lista3.size());
        int i=0;
        for (DataEmpleado x: lista3) 
        {
            tabla1.setValueAt(x.getEmpl_id_empl(), i, 0);
            tabla1.setValueAt(x.getEmpl_Nom(), i, 1);
            tabla1.setValueAt(x.getEmpl_ape(), i, 2);
            tabla1.setValueAt(x.getEmpl_tipo_id(), i, 3);
            tabla1.setValueAt(x.getEmpl_correo(), i, 4);
            tabla1.setValueAt(x.getEmpl_direc(), i,5);
            tabla1.setValueAt(x.getEmpl_tel(), i,5);
            i++;
        }
        
    }
    private void llenado(){
        Conexion con = new Conexion();
    try {
            ResultSet cad = con.listar("Select * from Empleado ");
            
                while (cad.next()) {

                    IdEntex.setText(cad.getString("id_empleado"));
                    NomEmtex.setText(cad.getString("nombre"));
                    TipIDtex.setText(cad.getString("tipo_id"));
                    CorreoEmtex.setText(cad.getString("correo_electronico"));
                    DirEmtex.setText(cad.getString("direccion"));
                    TelEmtex.setText(cad.getString("telefono"));
                    
                }
                    ResultSet c = con.listar("Select * from Contrato_modifica " );
            while (c.next()) {
            NContex.setText(c.getString("Num_Contrato_modifica"));
            Estatex.setText(c.getString("Estado"));
            TipCotex.setText(c.getString("Tipo_contrato"));
            
        }
                ResultSet ca = con.listar("Select * from  cargo ");
                while (ca.next()) {
                    
                CargEmtex.setText(ca.getString("Nombre_cargo"));
                
        }
        
                
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IdEntex = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NomEmtex = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CorreoEmtex = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DirEmtex = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TelEmtex = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CargEmtex = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        NContex = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Estatex = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TipCotex = new javax.swing.JTextField();
        TipIDtex = new javax.swing.JTextField();
        CodCartx = new javax.swing.JTextField();

        jLabel1.setText("ID Empleado");

        IdEntex.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        IdEntex.setEnabled(false);

        jLabel2.setText("Nombre");

        NomEmtex.setEnabled(false);

        jLabel3.setText("Tipo Id");

        jLabel4.setText("Correo electronico");

        CorreoEmtex.setEnabled(false);

        jLabel5.setText("Direccion");

        DirEmtex.setEnabled(false);
        DirEmtex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirEmtexActionPerformed(evt);
            }
        });

        jLabel6.setText("Telefono");

        TelEmtex.setEnabled(false);

        jLabel7.setText("Cargo Empleado");

        CargEmtex.setEnabled(false);

        jLabel8.setText("Numero de contrato");

        NContex.setEnabled(false);

        jLabel9.setText("Estado");

        Estatex.setEnabled(false);

        jLabel10.setText("Tipo de Contrato");

        TipCotex.setEnabled(false);

        TipIDtex.setEnabled(false);
        TipIDtex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipIDtexActionPerformed(evt);
            }
        });

        CodCartx.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CodCartx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(104, 104, 104))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(100, 100, 100))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(52, 52, 52))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(106, 106, 106))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(83, 83, 83))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IdEntex)
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TipIDtex)
                                .addGap(25, 25, 25))
                            .addComponent(NomEmtex)
                            .addComponent(CorreoEmtex)
                            .addComponent(DirEmtex)
                            .addComponent(TelEmtex))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(105, 105, 105))
                            .addComponent(CargEmtex, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NContex, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Estatex, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(51, 51, 51))
                            .addComponent(TipCotex, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IdEntex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CargEmtex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NomEmtex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NContex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TipIDtex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(12, 12, 12)
                        .addComponent(Estatex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CorreoEmtex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TipCotex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DirEmtex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TelEmtex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(CodCartx, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DirEmtexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirEmtexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DirEmtexActionPerformed

    private void TipIDtexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipIDtexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipIDtexActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CargEmtex;
    private javax.swing.JTextField CodCartx;
    private javax.swing.JTextField CorreoEmtex;
    private javax.swing.JTextField DirEmtex;
    private javax.swing.JTextField Estatex;
    private javax.swing.JTextField IdEntex;
    private javax.swing.JTextField NContex;
    private javax.swing.JTextField NomEmtex;
    private javax.swing.JTextField TelEmtex;
    private javax.swing.JTextField TipCotex;
    private javax.swing.JTextField TipIDtex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
